% quadsim_forces_moments.m
%
% Computes the total forces and moments acting on the quadrotor body.
%
% Forces are the sum of: gravity (NED -> body), aerodynamic rotor drag,
% and propeller thrust from all four motors.
%
% Moments are generated by differential thrust (roll and pitch) and
% differential rotor torque (yaw).
%
% Inputs:
%   uu = [wind_ned(1:3); deltas(1:4); x(1:12); time(1)]
%     wind_ned  - Total wind vector in NED frame, m/s
%     deltas    - Control channels [delta_e, delta_a, delta_r, delta_t]
%     x         - 12-state vehicle state vector
%     time      - Simulation time, s
%
% Outputs:
%   out = [f_b(1:3); m_b(1:3)]  (length 6)
%     f_b - Net forces along body x, y, z, N
%     m_b - Net moments about body x, y, z, N-m
%
% Adapted from Beard & McClain, "Small Unmanned Aircraft: Theory and
% Practice", Princeton Univ. Press, 2012
function out = quadsim_forces_moments(uu, P)

    % Unpack input vector
    %   uu = [wind_ned(1:3); deltas(1:4); x(1:12); time(1)]
    k=(1:3);          wind_ned=uu(k);   % Total wind vector, NED, m/s
    k=k(end)+(1:4);   deltas=uu(k);     % Control channels: [delta_e delta_a delta_r delta_t]
    k=k(end)+(1:12);  x=uu(k);          % 12-state vector
    k=k(end)+(1);     time=uu(k);       % Simulation time, s

    % Extract state variables
    pn    = x(1);   % North position, m
    pe    = x(2);   % East position, m
    pd    = x(3);   % Down position, m
    u     = x(4);   % Body-x groundspeed, m/s
    v     = x(5);   % Body-y groundspeed, m/s
    w     = x(6);   % Body-z groundspeed, m/s
    phi   = x(7);   % Roll angle, rad
    theta = x(8);   % Pitch angle, rad
    psi   = x(9);   % Yaw angle, rad
    p     = x(10);  % Body roll rate, rad/s
    q     = x(11);  % Body pitch rate, rad/s
    r     = x(12);  % Body yaw rate, rad/s

    vg_b = [u; v; w];   % Groundspeed vector in body frame, m/s
    w_b  = [p; q; r];   % Body angular rate vector, rad/s

    % Map abstract control channels to individual motor signals
    delta_e = deltas(1); % Pitch channel (+forward tilt)
    delta_a = deltas(2); % Roll channel  (+right roll)
    delta_r = deltas(3); % Yaw channel   (+clockwise yaw)
    delta_t = deltas(4); % Throttle,  0 to 1
    [delta_1, delta_2, delta_3, delta_4] = mapChannelsToMotors(delta_e, delta_a, delta_r, delta_t);

    % Compute propeller rotation rates from motor signals (rad/s)
    % Each motor can have an independent calibration bias (default 0).
    omega_1 = P.k_omega * delta_1 + P.prop_1_omega_bias;
    omega_2 = P.k_omega * delta_2 + P.prop_2_omega_bias;
    omega_3 = P.k_omega * delta_3 + P.prop_3_omega_bias;
    omega_4 = P.k_omega * delta_4 + P.prop_4_omega_bias;

    % Rotation matrix: NED -> body
    R_ned2b = eulerToRotationMatrix(phi, theta, psi);

    % Wind vector in body frame
    wind_b = R_ned2b * wind_ned;

    % Airspeed relative to the wind, in body frame
    va_rel_b = vg_b - wind_b;
    [Va, alpha, beta] = makeVaAlphaBeta(va_rel_b);

    % --- Gravity ---
    % Weight acts downward in NED; rotate to body frame
    f_grav_ned = P.mass * [0; 0; P.gravity];
    f_grav_b   = R_ned2b * f_grav_ned;

    % --- Aerodynamic drag ---
    % Horizontal rotor drag is proportional to horizontal airspeed relative
    % to the body (no vertical drag term — rotors dominate vertically).
    f_rotor_drag = -P.mu_rotorDrag * [u - wind_b(1); v - wind_b(2); 0];
    f_drag = f_rotor_drag;   % body drag is negligible for this frame

    % --- Propeller thrust ---
    % Thrust for each prop uses Beard & McClain's momentum-based propeller
    % model.  V_air_in is the axial inflow velocity (positive when air
    % flows up into the prop disk, i.e. the negative body-z component).
    V_air_in = -va_rel_b(3);
    f_prop_1 = P.rho*P.C_prop*P.S_prop * (V_air_in + (omega_1/P.k_omega)*(P.k_motor - V_air_in)) ...
                                        * ((omega_1/P.k_omega)*(P.k_motor - V_air_in));
    f_prop_2 = P.rho*P.C_prop*P.S_prop * (V_air_in + (omega_2/P.k_omega)*(P.k_motor - V_air_in)) ...
                                        * ((omega_2/P.k_omega)*(P.k_motor - V_air_in));
    f_prop_3 = P.rho*P.C_prop*P.S_prop * (V_air_in + (omega_3/P.k_omega)*(P.k_motor - V_air_in)) ...
                                        * ((omega_3/P.k_omega)*(P.k_motor - V_air_in));
    f_prop_4 = P.rho*P.C_prop*P.S_prop * (V_air_in + (omega_4/P.k_omega)*(P.k_motor - V_air_in)) ...
                                        * ((omega_4/P.k_omega)*(P.k_motor - V_air_in));

    % Total thrust acts along negative body-z (upward in level flight)
    f_prop_b = -(f_prop_1 + f_prop_2 + f_prop_3 + f_prop_4) * [0; 0; 1];

    % Net body force
    f_b = f_grav_b + f_drag + f_prop_b;

    % --- Propeller torques ---
    % Each prop produces a reaction torque proportional to omega^2.
    % Props 1 & 2 spin one direction; props 3 & 4 spin the opposite.
    torque_prop_1 = P.k_Tp * omega_1^2;
    torque_prop_2 = P.k_Tp * omega_2^2;
    torque_prop_3 = P.k_Tp * omega_3^2;
    torque_prop_4 = P.k_Tp * omega_4^2;

    % Motor arm moment arms (X-frame at 45 deg, split evenly)
    delta_y = P.L_to_motor * cos(45*pi/180);  % lateral arm, m
    delta_x = P.L_to_motor * sin(45*pi/180);  % longitudinal arm, m

    % Roll moment: differential thrust between left and right motor pairs
    m_x = (delta_y*(f_prop_3 + f_prop_2) - delta_y*(f_prop_1 + f_prop_4)) * [1; 0; 0];

    % Pitch moment: differential thrust between front and rear motor pairs
    m_y = (delta_x*(f_prop_1 + f_prop_3) - delta_x*(f_prop_2 + f_prop_4)) * [0; 1; 0];

    % Yaw moment: differential reaction torques between CW and CCW prop pairs
    m_z = ((torque_prop_1 + torque_prop_2) - (torque_prop_3 + torque_prop_4)) * [0; 0; 1];

    % Net body moment
    m_b = m_x + m_y + m_z;

    % Output: [forces(3); moments(3)]
    out = [f_b; m_b];

end
