% quadsim_wind.m
%
% Computes the total wind vector in NED coordinates.
%
% Combines the steady (user-specified) wind with the stochastic Dryden
% gust signal generated by the Simulink gust block. The Dryden model has
% been adapted for hovering vehicles: gusts are expressed in the NED frame
% rather than the body frame used in the fixed-wing formulation.
%
% Inputs:
%   uu = [gust_ned(1:3); time(1)]
%     gust_ned - Stochastic gust vector, NED frame, m/s
%     time     - Simulation time, s
%
% Outputs:
%   out = wind_ned (3x1), total wind vector in NED frame, m/s
%
% Steady wind components are set in init_quadsim_params.m via
%   P.wind_n, P.wind_e, P.wind_d
%
% Adapted from Beard & McClain, "Small Unmanned Aircraft: Theory and
% Practice", Princeton Univ. Press, 2012
function out = quadsim_wind(uu, P)

    % Unpack input vector
    %   uu = [gust_ned(1:3); time(1)]
    k=0+(1:3);    gust_ned=uu(k);   % Stochastic gust, NED frame, m/s
    k=k(end)+(1); time=uu(k);       % Simulation time, s

    % Steady wind vector from parameter structure
    ws_ned = [P.wind_n; P.wind_e; P.wind_d];

    % Total wind = steady component + stochastic gust
    wind_ned = ws_ned + gust_ned;

    out = wind_ned;  % Length 3

end
